name: Format PHP (Pint)

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

permissions:
  contents: write

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress

      - name: Run Pint
        working-directory: ./backend
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(backend): Format PHP files with Pint"
          file_pattern: "backend/**/*.php"
