name: Format Frontend (Prettier)

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install

      - name: Run Prettier
        working-directory: ./frontend
        run: bun run format:write

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(frontend): Format files with Prettier"
          file_pattern: "frontend/**/*.{js,ts,jsx,tsx,css,json,md}"
