name: release-installer

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag para el Release v0.1.0 (ej.: v0.1.0)"
        required: true
        default: "v0.1.0"
      prerelease:
        description: "Marcar el Release como pre-release"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.2.15"

      - name: Build installer executable
        run: bun run build:installer

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
          files: |
            dist/quick-install.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
